# name: DevopsPipeline
# on:
#   push:
#     branches:
#       - "main"
# jobs:
#   BuildDevopsPipeline:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#     - name: Build code
#       run: npm ci
#     - name: build project
#       run: npm build



